spring:
  application:
    name: prodyctvs-api
  datasource:
    url: jdbc:mysql://db:3306/prodyctvs_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: prodyctvs123
    driverClassName: com.mysql.jdbc.Driver 
api:
  jwt:
    secret: 
    issuer: api-prodyctvs